### ISSUE TITLE
Change font?

### ISSUE THREAD

**Issue by joelnitta** [mps9506/quarto-cv#7]
Thanks for the great template!

How can I change the font?

**Comment by mps9506** [comment]
@joelnitta You *should* be able to add the following in the yaml header

```yaml
fontfamily: lmodern
```

Where fontfamily corresponds to one of the font families in the latex font catalogue: https://tug.org/FontCatalogue/latinmodernroman/

But it isn't working when I tried. I can see tinytex download the required files so something is wrong in the template.

I'll plan on updating this to use both local fonts and latex package fonts when I have the chance. Thanks for the report.

**Comment by joelnitta** [comment]
Thanks!

BTW if you're interested in seeing a use-case for the template along with a few tweaks, please check out my new CV :) https://github.com/joelnitta/joelnitta-cv

**Comment by mps9506** [comment]
@joelnitta I just pushed a new release that enables specifying fonts. See the readme or new template.qmd for info on how to use. You will need to reinstall/update the template in your project directory to utilize it:
```
mps9506@DESKTOP-I3HUM8A:~/temp-quarto-fonts$ quarto install extension mps9506/quarto-cv

Quarto extensions may execute code when documents are rendered. If you do not 
trust the authors of the extension, we recommend that you do not install or 
use the extension.
 ? Do you trust the authors of this extension (Y/n) › Yes
[✓] Downloading
[✓] Unzipping
    Found 1 extension.

The following changes will be made:
quarto-cv   [Update] 1.0.1 -> 1.0.2 (format)
 ? Would you like to continue (Y/n) › Yes

[✓] Extension installation complete.
Learn more about this extension at https://www.github.com/mps9506/quarto-cv

```
